# Generated by Django 3.0.3 on 2020-02-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('newid', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='abcd@abcd.com', max_length=254)),
                ('hostel_name', models.CharField(default='default hostel', max_length=200)),
                ('hostel_address', models.CharField(default='default address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('submission_date', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('ans', models.CharField(default='default ans', max_length=1000)),
                ('is_corrected', models.BooleanField(default=False)),
                ('marks', models.IntegerField(default=-1)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appy.Student')),
            ],
        ),
    ]
